### PR TITLE
initialize barebone structure, and a few utility functions

### PR DESCRIPTION
**Pull request by J-ZhengLi**
changelog: Init bare-bone structure, add basic dependencies, and add a few utility functions

### CODE REVIEW

**Review by genedna — COMMENTED** [review]
@J-ZhengLi 

Please signoff all commits, and there is a help [link](https://github.com/open-rust-initiative/mega#rebase-the-branch).

And copy the content into the README.md file for other contributors

**Comment by J-ZhengLi** [comment]
> @J-ZhengLi
> 
> Please signoff all commits, and there is a help [link](https://github.com/open-rust-initiative/mega#rebase-the-branch).
> 
> And copy the content into the README.md file for other contributors

@genedna 

Thanks~ I did use `git commit -s ...` but maybe I did it wrong for some reason, could you  please check it again?

I've also add a commit updating the README with a slightly modified `contributing` guidance from the repository that you mentioned, please also take a look.

**Review by genedna — APPROVED** [review]
LGTM

**Comment by genedna** [comment]
@J-ZhengLi 

The PR still blocked, because your must sign your all commits follow the [hint](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

**Pull request merged**
